### ISSUE TITLE
Specify the id into iOS and androidId

### ISSUE THREAD

**Issue by Tsagaanbayr1** [X-SLAYER/app_version_checker#1]
My app has two separate ids for Google Play and App Store. for iOS: "mn.asap.care", and for android: "mn.clinica.care". But the plugin has only one input named: "appId".

**Comment by X-SLAYER** [comment]
yes good point i will added it asap

**Comment by timobaehr** [comment]
What is about this issue? Do you still have to add two checker instances in your app for iOS or Android?

Is the README outdated?

```dart
AppVersionChecker({
    this.currentVersion,
    this.appId,
    this.androidStore = AndroidStore.googlePlayStore,
  });
```
