### ISSUE TITLE
No longer working on IOS side

### ISSUE THREAD

**Issue by Haris2v** [X-SLAYER/app_version_checker#11]
Every time I try to check update on the iSO side, it give me the following response. 

Can't find an app in the App Store with the id xxxx

Here I have replaced my original app id with xxxx for privacy reasons. I also tried app ids from different other apps, but it seems Apple is no longer proving response on this url. 

I have tried mine and 8 ball pool game package name in the following way even in the browser. 

https://itunes.apple.com/lookup?bundleId=com.miniclip.eightballpool

But every time it give the same response as written below. 

```
{
 "resultCount":0,
 "results": []
}

```

Please check and fix this issue ASAP :)

**Comment by timobaehr** [comment]
Are you sure this is the correct bundle id of your app? Apple API still works as well as the plugin.

**Comment by Haris2v** [comment]
Yeah. And I have already explained that I tried with mine real ID and even ID of other popular apps and games but it didn't work with anyone

**Comment by KimSungJin0** [comment]
I think there are two cases where you can't get app information with url.

In the first case, if you are registered only with a specific country server, you may need to mark that server in url.
`"https://itunes.apple.com/$local/lookup?bundleId=$packageName"`

Second, please try using apple id instead of bundle id.
`"https://itunes.apple.com/$local/lookup?id=$appleId"`

**Comment by SimonTellier** [comment]
I agree with @KimSungJin0. I had to modify the code to make it work for my application. 
I had to add before "/lookup" my region "/fr/lookup"

**Comment by Haris2v** [comment]
Yes I have confirmed that we can get app information using "https://itunes.apple.com/$local/lookup?id=$appleId"
Where $local is region, in my case it is PK
Thank you @KimSungJin0  and @SimonTellier
