### ISSUE TITLE
Cant Run on IOS

### ISSUE THREAD

**Issue by basheerbsr79** [X-SLAYER/app_version_checker#2]
[!] No podspec found for `flutter_app_version_checker` in `.symlinks/plugins/flutter_app_version_checker/ios`

above error got while running ios build

**Comment by X-SLAYER** [comment]
I need to recheck it because I don't have a mac to test on ios for the moment

**Comment by ajaykumarparashar11** [comment]
I am facing the same issue
 
[!] No podspec found for `flutter_app_version_checker` in `.symlinks/plugins/flutter_app_version_checker/ios`

you did not add the .podspec file to your project. —samples like.
 

Sample 1:

#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'image_picker'
  s.version          = '0.0.1'
  s.summary          = 'Flutter plugin that shows an image picker.'
  s.description      = <<-DESC
A Flutter plugin for picking images from the image library, and taking new pictures with the camera.
Downloaded by pub (not CocoaPods).
                       DESC
  s.homepage         = 'https://github.com/flutter/plugins'
  s.license          = { :type => 'BSD', :file => '../LICENSE' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :http => 'https://github.com/flutter/plugins/tree/master/packages/image_picker' }
  s.documentation_url = 'https://pub.dev/packages/image_picker'
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.platform = :ios, '9.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
end


Sample 2: 

#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'shared_preferences'
  s.version          = '0.0.1'
  s.summary          = 'Flutter Shared Preferences'
  s.description      = <<-DESC
Wraps NSUserDefaults, providing a persistent store for simple key-value pairs.
                       DESC
  s.homepage         = 'https://github.com/flutter/plugins'
  s.license          = { :type => 'BSD', :file => '../LICENSE' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :http => 'https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences' }
  s.documentation_url = 'https://pub.dev/packages/shared_preferences'
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  
  s.platform = :ios, '9.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end

**Comment by samatzhusup** [comment]
same error

**Comment by mantreshkhurana** [comment]
Please fix this issue asap am in the process of app production.

**Comment by ernestoA92** [comment]
same here

**Comment by ernestoA92** [comment]
> I need to recheck it because I don't have a mac to test on ios for the moment

then you should remove ios support 😡

**Comment by X-SLAYER** [comment]
it's not about support sorry for that cuz I don't have a mac to test on iPhone otherwise you can just take the lib code and put it in your app and it will works fine because it's a dart code in the end not a native

**Comment by kalibroida** [comment]
[!] No podspec found for flutter_app_version_checker in .symlinks/plugins/flutter_app_version_checker/ios

above error got while running ios build

**Comment by robsonfj** [comment]
Same error here

**Comment by nashirdrabi** [comment]
just change the name of app_version_checker.podspec to flutter_app_version_checker.podspec

**Comment by RYO1223** [comment]
Has a new version been submitted?

**Comment by RYO1223** [comment]
@X-SLAYER

**Comment by X-SLAYER** [comment]
yes I have published a new version with the latest IOS fix [flutter_app_version_checker (v0.3.2)](https://pub.dev/packages/flutter_app_version_checker)
